name: deploy
on:
  push:
    branches: ["staging"]

jobs:
  deployment:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME}}
          password: ${{ secrets.SERVER_PASSWORD}}
          port: ${{ secrets.SERVER_PORT  }}
          script: |
            whoami
            cd tp-core && git pull
            cd web && yarn install && yarn build
            cd ..
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker rm ${{ vars.CONTAINER_NAME }} || true
            docker build --tag tp-core:latest .
            docker run -d -p 8080:8080 --network tp-network --name container-tp-core tp-core:latest